// vue_app_/src/components/CategoryList.vue
<template>
  <div>
    <button v-for="c in categories"
            v-bind:key="c"
            v-bind:class="getButtonClasses(c)"
            @click="selectCategory(c)">
      {{ c }}
    </button>
  </div>
</template>
<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class CategoryList extends Vue {
  @Prop()
  private categories!: string[];
  @Prop()
  private selected: string = this.categories[0];

  selectCategory(category: string) {
    this.$emit("selectCategory", category);
  }

  getButtonClasses(category: string): string {
    let btnClass = this.selected === category ? "btn-primary" : "btn-secondary";
    return `btn btn-block ${btnClass}`;
  }
}
</script>

// web_app/src/categoryList.tsx
import {createElement} from "./tools/jsxFactory";

export class CategoryList {
  props: {
    categories: string[];
    selectedCategory: string,
    callback: (selected?: string) => void
  }

  getContent(): HTMLElement {
    return <div>
      {["All", ...this.props.categories].map(c => this.getCategoryButton(c))}
    </div>
  }

  getCategoryButton(cat?: string): HTMLElement {
    let selected = this.props.selectedCategory === undefined ? "All" : this.props.selectedCategory;
    let btnClass = selected === cat ? "btn-primary" : "btn-secondary";
    return <button className={`btn btn-block ${btnClass}`}
                   onclick={() => this.props.callback(cat)}>
      {cat}
    </button>
  }
}
