// vue_app_/src/components/ProductItem.vue
<template>
  <div class="card m-1 p-1 bg-light">
    <h4>
      {{ product.name }}
      <span class="badge badge-pill badge-primary float-right">
        ${{ product.price.toFixed(2) }}
      </span>
    </h4>
    <div class="card-text bg-white p-1">
      {{ product.description }}
      <button class="btn btn-success btn-sm float-right"
              @click="handleAddToCart">
        Add To Cart
      </button>
      <select class="form-control-inline float-right m-1"
              v-model.number="quantity">
        <option>1</option>
        <option>2</option>
        <option>3</option>
      </select>
    </div>
  </div>
</template>
<script lang="ts">
import {Product} from "@/data/entities";
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
export default class ProductItem extends Vue {
  @Prop() private product!: Product;
  quantity: number = 1;

  handleAddToCart() {
    this.$emit("addToCart", {product: this.product, quantity: this.quantity});
  }
}
</script>

// react_app/src/productItem.tsx
import React, {Component, ChangeEvent} from "react";
import {Product} from "./data/entities";

interface Props {
  product: Product,
  callback: (product: Product, quantity: number) => void
}

interface State {
  quantity: number
}

export class ProductItem extends Component<Props, State> {
  constructor(props: Props) {
    super(props);
    this.state = {
      quantity: 1
    }
  }

  render() {
    return <div className="card m-1 p-1 bg-light">
      <h4>
        {this.props.product.name}
        <span className="badge badge-pill badge-primary float-right">
${this.props.product.price.toFixed(2)}
</span>
      </h4>
      <div className="card-text bg-white p-1">
        {this.props.product.description}
        <button className="btn btn-success btn-sm float-right"
                onClick={this.handleAddToCart}>
          Add To Cart
        </button>
        <select className="form-control-inline float-right m-1"
                onChange={this.handleQuantityChange}>
          <option>1</option>
          <option>2</option>
          <option>3</option>
        </select>
      </div>
    </div>
  }

  handleQuantityChange = (ev: ChangeEvent<HTMLSelectElement>): void =>
    this.setState({quantity: Number(ev.target.value)});
  handleAddToCart = (): void =>
    this.props.callback(this.props.product, this.state.quantity);
}
